### ISSUE TITLE
Requesting for dynamic gradient colors

### ISSUE THREAD

**Issue by Thet-Tun-Aung** [jeffshee/NextGenVisualizer#2]
Thanks you for your supporting sir,
Now , I need a solution how to change gradient colors programmatically.
So that can change gradient colors adaptive to the album art in run time.

Thank you so much. 😌

**Comment by jeffshee** [comment]
Hi!
Dynamic gradient colors is possible. To do that, you will just have to keep a reference of the `gradient` in order to perform modification later. (This is also true for other `painter`)
Here's the example:
First, create a `gradient` object and keep the reference
```kotlin
var gradient = Gradient(
        preset = Gradient.RADIAL,
        // You can change your color here, e.g. inner and outer color
        color1 = Color.rgb(153, 51, 255),
        color2 = Color.rgb(255, 0, 127)
    )
```
 Second, use the created `gradient` when creating your `painter`
```kotlin
Beat(
        Compose(
            Blend(
                FftCLine().apply { paint.strokeWidth = 8f;paint.strokeCap = Paint.Cap.ROUND },
                gradient  // <---
            ),
            Icon(circleBitmap)
        )
    )
```
Lastly, modify the `gradient`'s variable will change the colors. For instance, here I set it to a random color when the visualizer was clicked
```kotlin
visual.setOnClickListener {
            gradient.apply {
                color1 = Color.rgb(
                    Random.nextInt(0, 255), Random.nextInt(0, 255), Random.nextInt(0, 255)
                );color2 = Color.rgb(
                Random.nextInt(0, 255), Random.nextInt(0, 255), Random.nextInt(0, 255)
            )
            }
        }
```
Here is the result
![20190720_144227](https://user-images.githubusercontent.com/25530920/61574778-1360bc80-aaff-11e9-9065-079f45f83348.gif)

Happy coding! 😊

**Comment by Thet-Tun-Aung** [comment]
Thanks so much sir, I'll try now. 
Thanks for your answering. You are awesome. 😊
Happy coding too !
