### ISSUE TITLE
question about Kotlin 

### ISSUE THREAD

**Issue by Ooggle** [jeffshee/NextGenVisualizer#3]
I saw a long time ago an app on the Playstore called "AudioVision music player". It's a music player with a visualizer very very similar to this one.
So my question is, there is any link between this repo and AudioVision ?

**Comment by jeffshee** [comment]
Hi
The answer is no. There isn't any relation between this repo and AudioVision.
However, I do get some inspiration from various sources, for instance YouTube videos, websites and music players like AudioVision, then I try to reimplement the components which would be required in order to create such visualizers. 😃
So, with this lib, of course you can create visualizers similar to AudioVision's, but there's no limitation. 😏

**Comment by Ooggle** [comment]
Oh i see, that very good. Thanks for that clear and concise answer, i look forward to see this lib improve !
