### ISSUE TITLE
Replacing View with SurfaceView

### ISSUE THREAD

**Issue by mahyarmlk** [jeffshee/NextGenVisualizer#6]
Hi
How can achive this?
I want a dedicated thread for drawing painters.

**Comment by jeffshee** [comment]
Hi!
I'm afraid that there isn't an easy way. If you need the `SurfaceView` instead, the best way you can achieve this is to implement your own `VisualizerView.kt` I believe. You can start by trying to inherit the `SurfaceView` instead of `View`.

Keep in mind though, `SurfaceView` doesn't support Hardware Acceleration. And depends on the painters you are trying to use, it can cause lower performance. So, I would strongly suggest that you should stick with `View` instead. (And this is also why I choose `View` in the first place, `SurfaceView`  just doesn't suit to draw in high speed.)

Hope this answers your question. ^^

**Comment by jeffshee** [comment]
Hi @mahyarmlk 
So how was it going? I'm closing this issue for now. 
Should you have any questions, please don't hesitate to reopen this issue.
Thanks.
